### ISSUE TITLE
Adaptation in Swift of "emo_emojiRanges"

### ISSUE THREAD

**Issue by ericdke** [GabrielMassana/SearchEmojiOnString-iOS#1]
Hello,

I've made [WithOrWithoutEmoji](https://github.com/ericdke/WithOrWithoutEmoji), a simple Swift String and NSString extension based on your Objective-C work in this project.

I wanted to thank you for your work and for licencing it as MIT (my extension is also MIT).

Don't hesitate to tell me what you think about this.

Cheers!
## 

Eric Dejonckheere

**Comment by GabrielMassana** [comment]
Hello Eric,

Great initiative. Thanks for letting me know and to include my project in your documentation.

Regards,

Gabriel Massana
